[switches]
##### General switches
shortwave = true
longwave = true
fluxes = true

cloud-optics = true
delta-cloud = false

aerosol-optics = true
delta-aerosol = false

##### test_rte_rrtmgp only (CPU & GPU)
output-optical = false
output-bnd-fluxes = false

##### test_rte_rrtmgp only (GPU)
timings = false

##### Forward raytracer only

# switch on ray tracer. Specifiy ray counts under [ints]: samples per pixel for sw, for lw provide n to use 2^n samples
sw-raytracing = true
lw-raytracing = true

# Also perform two-stream computations for shortwave.
sw-two-stream = false

# Independent column mode
independent-column = false
# Tilted independent column mode
tica = false

# Enable scattering for longwave. If enabled, 1D solver will also switch from no-scat solution to two-stream formulation
lw-scattering = true

# Only perform ray tracing when the minimum gasous mean free path is larger than (min-mfp-grid-ratio * grid spacing) and use a 1D solutions otherwise.
# Specify threshold ratio under [floats]
min-mfp-grid-ratio = true

# liq and ice flags are automatically switch on when cloud-optics is set to true
# to run either liquid or ice cloud optics
liq-cloud-optics = false
ice-cloud-optics = false

##### Common raytracer (forward & backward) switches
cloud-mie = false

# Save optical properties and fluxes for a single g-point. Specify under [ints]
single-gpt = false

# Enable profiling
profiling = false

##### Backward raytracer only
raytracing = true

# Read variable "surface_type" to determine scattering type and spectral albedo for each surface grid cell.
# Set either to 0 (water; spectrally constant albedo; specular reflection) or a number between 1 (soil-like spectral albedo; lambertian) and 2 (grass-line spectral albedo; lambertian).
lu-albedo = true

# broadband radiance computation (sum over all g-points)
broadband = true

# image computation: run only g-points in visible spectrum and convert to XYZ tristimulus values
image = true

[ints]
single-gpt = 1

sw-raytracing = 256
lw-raytracing = 22

raytracing = 128

[floats]
min-mfp-grid-ratio = 1.0
