[clouds]
liquid_cloud_optics = true
ice_cloud_optics = true
delta_cloud = false
tilted_columns = false
cloud_mie = false

[aerosols]
aerosol_optics = false
delta_aerosol = false

[shortwave]
shortwave = true

# compute ray tracer fluxes using "samples" photons per pixel per spectral quadrature point
raytracing = true
samples = 256

# ray tracing in independent column mode
rt_independent_column = false

# compute plane parallel (two-stream) fluxes
plane_parallel = false

# only compute specified g-point
single_gpt = -1

[longwave]
longwave = true

# compute ray tracer fluxes using 2**samples photons per spectral quadrature point
raytracing = true
samples = 22

# ray tracing in independent column mode
rt_independent_column = false

# enable scattering
scattering = false

# compute plane parallel fluxes (two-stream or no-scat solution depending on "scattering")
plane_parallel = false

# only compute specified g-point
single_gpt = -1

# threshold ratio between lowest gaseus mean free path and horizontal grid spacing
# if this ratio falls below the thershold for a g-point, plane parallel fluxes are used for that g-point instead of the raytracer
min_mf_grid_ratio = 0.0

[backward]
# enable backward ray tracing using "samples" photons per pixel"
bw_raytracing = true
samples = 16

# raytrace bands that fall within visible spectrum and convert radiances to XYZ tristimulus values
image = true

# compute broadband radiances
broadband = true

# output additional cloud information for each camera pixel
cloud_cam = true

# read surface type from "land_use_map" input variable and use corresponding spectral albedo and scattering type (lambertian, specular)
lu_albedo = true

[solar_angles]
# solar zenith angle in degrees. mu0 from input file is used if sza < 0
sza = 45

# solar azimuth angle in degrees. azi from input file is used if azi < 0
azi = 135

[camera]
cam_field_of_view = 50.0

# camera type: (0) fish eye camera, (1) rectangular camera, (2) top-of-atmosphere upwelling radiances
cam_type = 1

# x,y,z positions of virtual camera
cam_px = 0.0
cam_py = 0.0
cam_pz = 2500.0

# width, height (pixels) of virtual camera
cam_nx = 512
cam_ny = 512

# yaw, pitch and roll angles (degrees) of the virtual camera
cam_yaw = 135.0
cam_pitch = 55.0
cam_roll = 0.0

