[switches]
shortwave = true
longwave = true
fluxes = true
liquid_cloud_optics = false
ice_cloud_optics = false
aerosol_optics = false
delta_cloud = true
delta_aerosol = false

# gpu_only (test_rte_rrtmgp_gpu)
timings = false

# raytracer (test_rte_rrtmgp_rt_gpu)
sw_two_stream = false
sw_raytracing = true
lw_raytracing = true
independent_column = false
liq_cloud_optics = false
ice_cloud_optics = false
lw_scattering = false
cloud_mie = false
single_gpt = false
profiling = false
min_mfp_grid_ratio = true
tica = false

[ints]
sw_raytracing = 256
lw_raytracing = 22
single_gpt = 1

[floats]
min_mfp_grid_ratio = 1.0
