[clouds]
liquid_cloud_optics = true
ice_cloud_optics = true
delta_cloud = false
tilted_columns = false
cloud_mie = false

[aerosols]
aerosol_optics = false
delta_aerosol = false

[shortwave]
shortwave = true

# compute ray tracer fluxes using "samples" photons per pixel per spectral quadrature point
raytracing = false

# compute plane parallel (two-stream) fluxes
plane_parallel = true

[longwave]
longwave = true

# compute ray tracer fluxes using 2**samples photons per spectral quadrature point
raytracing = false

# compute plane parallel fluxes (two-stream or no-scat solution depending on "scattering")
plane_parallel = true

